// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TitheEnvelope.DAL.Models;

namespace TitheEnvelopeApi.Migrations
{
    [DbContext(typeof(TitheContext))]
    [Migration("20190913190506_TitherPaymentDetailSeed")]
    partial class TitherPaymentDetailSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TitheEnvelopeApi.Models.TithePaymentDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<DateTime>("DateInserted")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateOfPayment")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("TitherDetailId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TitherDetailId");

                    b.ToTable("TithePaymentDetail","dbo");

                    b.HasData(
                        new { Id = 1L, Amount = 100m, DateInserted = new DateTime(2019, 9, 13, 20, 5, 0, 511, DateTimeKind.Local), DateOfPayment = new DateTime(2019, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), IsDeleted = false, PaymentMethod = "Cash", TitherDetailId = 1L }
                    );
                });

            modelBuilder.Entity("TitheEnvelopeApi.Models.TitherDetail", b =>
                {
                    b.Property<long>("TitherDetailId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateInserted")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameOfTither")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("TitherDetailId");

                    b.ToTable("TitherDetail","dbo");
                });

            modelBuilder.Entity("TitheEnvelopeApi.Models.TithePaymentDetail", b =>
                {
                    b.HasOne("TitheEnvelopeApi.Models.TitherDetail", "TitherDetail")
                        .WithMany("TithePaymentDetails")
                        .HasForeignKey("TitherDetailId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
